### ISSUE TITLE
Does this work with Android with mini buttoon

### ISSUE THREAD

**Issue by ashishusoni** [ZaynJarvis/Flutter-Sign-in-Button#10]
On Android emulator i do not see mini==true is working see the screenshot attached

![image](https://user-images.githubusercontent.com/47181950/53581667-ff1a2400-3b4b-11e9-95b6-c95e67b49e6f.png)

**Comment by ZaynJarvis** [comment]
Could you check if the version of the package is the latest?

**Comment by ashishusoni** [comment]
yes it is at the latest version

**Comment by ZaynJarvis** [comment]
May be caused by CrossAxisAlignment.

**Comment by ZaynJarvis** [comment]
Close since no follow up.
