### ISSUE TITLE
Overflow error

### ISSUE THREAD

**Issue by Raviteja11122** [ZaynJarvis/Flutter-Sign-in-Button#16]
@ZaynJarvis 
Getting error in lower screen resolutions,
the button text is overflowed.

**Comment by ZaynJarvis** [comment]
Try to change the text inside the button like just `Sign in`

**Comment by ghecreagheorghe** [comment]
is there a fix for this? same here, on flutter web v2.0.3

**Comment by MiguelAlvesMiguel** [comment]
I have no idea why this was closed. @ZaynJarvis

**Comment by MiguelAlvesMiguel** [comment]
Why was this closed? @ZaynJarvis It's still a problem and changing the text is not really a solution.

**Comment by ZaynJarvis** [comment]
Should be solve by #68

**Comment by ZaynJarvis** [comment]
> Why was this closed? @ZaynJarvis It's still a problem and changing the text is not really a solution.

This issue will merge with #68, fix might be applied to both.

**Comment by MamikonP** [comment]
As there is no any solution for this, I can provide some example to solve that problem. You can use SingInButton another way.

`GestureDetector(
  onTap: () => signInWithGoogle(),
  child: Card(
	  elevation: 2,
	  child: Row(
		  mainAxisAlignment: MainAxisAlignment.center,
		  children: <Widget>[
			  const Image(
				  image: AssetImage(
					  'assets/logos/google_light.png', 
					  package: 'flutter_signin_button' // PAY ATTENTION to this package, because without provide this it can't work.
				  )
			  ),
			  Flexible(
				  child: Text(
					  'LOOOOOONG TEEEEXT'
				  ),
			  )
		  ],
	  ),
  ),
  ),`
