### ISSUE TITLE
Buttons.Email onPressed needs changing

### ISSUE THREAD

**Issue by dali546** [ZaynJarvis/Flutter-Sign-in-Button#2]
For all other buttons like Buttons.Google, the onPressed method works fine. but not for Buttons.Email.

after looking at source problem is in ```button_view.dart``` file 

at line 39

```
onPressed: () {},
```

onPressed is defined... it should be like the others

```onPressed: onPressed,```

**Comment by ZaynJarvis** [comment]
Oh maybe I missed this one thank you for letting me know.

**Comment by ZaynJarvis** [comment]
This issue is solved by pull request #4. 
Hence the issue will be closed.
