### ISSUE TITLE
Uniform size of sign in buttons 

### ISSUE THREAD

**Issue by zugspitze** [ZaynJarvis/Flutter-Sign-in-Button#23]
Thanks for awesome package. I think it would look better if the buttons have similar size (height and width). Currently Google sign in button is very big compared to others.

**Comment by ZaynJarvis** [comment]
Hi, Thanks for your comment zugspitze. 
Previously it was intended for backwards compatibility. Solved in version 1.0.0

**Comment by zugspitze** [comment]
@ZaynJarvis Thanks again for fixing the issue, when do you think version 1.0.0 will be available?
 
```Running "flutter pub get" in my_project...                  
Because my_project depends on flutter_signin_button ^1.0.0 which doesn't match any versions, version solving failed.```

**Comment by ZaynJarvis** [comment]
Just updated.

**Comment by zugspitze** [comment]
Thanks you :-)
