### ISSUE TITLE
Google icon

### ISSUE THREAD

**Issue by erperejildo** [ZaynJarvis/Flutter-Sign-in-Button#24]
Facebook for example looks fine, when you do a long press the icon is included on its button but this effect doesn't work like that for Google. It looks like a different button inside the login button

![Untitled-2](https://user-images.githubusercontent.com/5629919/69139193-48d2e200-0ac0-11ea-867f-5629fc756941.jpg)

**Comment by ZaynJarvis** [comment]
Yes, for Google it's an image while the others are icons.


Regards

**Comment by erperejildo** [comment]
is it not possible to have an icon as well for this one? It also looks smaller and with different padding

**Comment by ZaynJarvis** [comment]
It is designed to confront Google design guidelines. For now i don't have solution to make it a icon.


Regards

**Comment by bounty1342** [comment]
@ZaynJarvis maybe there is something to do with :

ShaderMask(
                    child: Icon(FontAwesomeIcons.google, size: 255),
                    shaderCallback: (Rect bounds) {
                      return AppTheme.primaryGradientLightInverted.createShader(bounds);
                    },
                    blendMode: BlendMode.srcATop,


Maybe by changing the gradient to an ImageShader it will do the trick. What do you think ?
Little bit overkill ?

Regards

**Comment by ZaynJarvis** [comment]
looks cool! You can test it on your device, a pr is greatly welcomed!


Regards

**Comment by ZaynJarvis** [comment]
#27 See if this helps

**Comment by moha1313128** [comment]
Unable to load asset: packages/flutter_signin_button/assets/logos/3.0x/google_dark.png

**Comment by ZaynJarvis** [comment]
> Unable to load asset: packages/flutter_signin_button/assets/logos/3.0x/google_dark.png

fixed in the newest release
