### ISSUE TITLE
No Icons other than Google

### ISSUE THREAD

**Issue by findmycook** [ZaynJarvis/Flutter-Sign-in-Button#28]
There is no icon in the library other than Google.

**Comment by Jurdefur** [comment]
Add font awesome to your dependencies

dependencies:
  font_awesome_flutter: ^8.7.0

**Comment by ZaynJarvis** [comment]
dependency update will be in next release

**Comment by ZaynJarvis** [comment]
fa: ^8.7.0 doesn't seem to conflict tho
