### ISSUE TITLE
Unable to load asset: packages/flutter_signin_button/assets/logos/3.0x/google_light.png

### ISSUE THREAD

**Issue by Rohit-ChauhanRC** [ZaynJarvis/Flutter-Sign-in-Button#40]
I try to google button and then show me error.

**Comment by ZaynJarvis** [comment]
Could you provide the error and the file structure so we can help find the issue.

**Comment by peachmakkoli** [comment]
I'm getting a similar error! Here's a screenshot of the stack trace:

<img width="1162" alt="Screen Shot 2020-07-21 at 3 09 14 PM" src="https://user-images.githubusercontent.com/29715296/88112268-5ca97900-cb64-11ea-97cd-24a78e9dd9f4.png">

Thanks!

**Comment by ZaynJarvis** [comment]
fixed

**Comment by heinaungzan** [comment]
not solve for me now
