### ISSUE TITLE
unable to load google logo while using the SignInButton with custom text

### ISSUE THREAD

**Issue by harshit2106** [ZaynJarvis/Flutter-Sign-in-Button#42]
<img width="960" alt="issue" src="https://user-images.githubusercontent.com/50888193/86050832-0c159300-ba72-11ea-870b-165eac19942b.png">
though this is a great package and i use this package quite a lot and most of the time i face this issue but when i restart my editor(vs code) and re-run the app then it works fine

**Comment by ZaynJarvis** [comment]
This is wierd. It looks like you failed to import the package in this file, could you check pubspec.yaml?

**Comment by lahirudilshan** [comment]
same issue
