### ISSUE TITLE
add microsoft sign in

### ISSUE THREAD

**Issue by Shakle** [ZaynJarvis/Flutter-Sign-in-Button#43]
Microsoft sign in is also popular, add please

**Comment by champ96k** [comment]
> Microsoft sign in is also popular, add please

@Shakle 
we already added Hotmail button and that Hotmail button is belongs to Microsoft button , if am not wrong

**Comment by Shakle** [comment]
@champ96k 
I'm afraid that Hotmail is an old Microsoft mail device that no longer exists for the last 10 years, it was changed by outlook.
But Microsoft has their button like Apple and Google.

It looks like ![](https://infobase-learn360.zendesk.com/hc/article_attachments/360043582213/image-0.png)

**Comment by champ96k** [comment]
@Shakle 

Thanks for inform , we will implement soon

**Comment by champ96k** [comment]
@Shakle

done waiting for @ZaynJarvis reply to merge my pull request

**Comment by ZaynJarvis** [comment]
thx and merged
