### ISSUE TITLE
[Feature request]Font option

### ISSUE THREAD

**Issue by shinriyo** [ZaynJarvis/Flutter-Sign-in-Button#47]
Add Font Option.
I guess it uses os font.

**Comment by ZaynJarvis** [comment]
as you can see this package is not complex at all, if there are certain specific needs to customise feel free to vendor the source code for your own app.

**Comment by ZaynJarvis** [comment]
if later I found this is a need for most of the package users, we could add this as an option as well.
Hence, this feature request could be left here for a reference.

**Comment by ZaynJarvis** [comment]
hold the opinion, should use ButtonBuilder if need to change font.
