### ISSUE TITLE
Google and Facebook small button is not working

### ISSUE THREAD

**Issue by Faizi-Apps** [ZaynJarvis/Flutter-Sign-in-Button#51]
Hello
When i use mini: true then it generate following error
Google and FacebookNew buttons do not support mini mode
'package:flutter_signin_button/button_view.dart':
Failed assertion: line 47 pos 13: 'mini != true ||
                !(button == Buttons.Google ||
                    button == Buttons.GoogleDark ||
                    button == Buttons.FacebookNew)'

**Comment by ZaynJarvis** [comment]
yes, that's by design, they don't have mini square button. It's restricted
by Google Facebook button design rules.

**Comment by Faizi-Apps** [comment]
Oky....
