### ISSUE TITLE
Logo isn't affected by rounded border shape

### ISSUE THREAD

**Issue by JulianAssmann** [ZaynJarvis/Flutter-Sign-in-Button#62]
When using a signin button with the `shape` set to  `RoundedRectangleBorder`, the shape does not affect the logo of the auth provider.

```
SignInButton(
    theme.brightness == Brightness.light ? Buttons.Google : Buttons.GoogleDark,
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
)
```

![signin_button](https://user-images.githubusercontent.com/15306765/104235916-f6881980-5455-11eb-97fd-11d1cb25f021.PNG)

**Comment by ZaynJarvis** [comment]
yea, cuz logo is an image. And google design guideline https://developers.google.com/identity/branding-guidelines doesn't support that I think

**Comment by sowsan** [comment]
If we increase the width by putting the button in a column with crossalignment to strech does the trick.
