### ISSUE TITLE
Phone button

### ISSUE THREAD

**Issue by jeanmatthieud** [ZaynJarvis/Flutter-Sign-in-Button#67]
Is it possible to add a phone button ?

**Comment by ZaynJarvis** [comment]
can use ButtonBuilder

**Comment by a7medpa** [comment]
> can use ButtonBuilder

At least in the button builder couldn't you add an Icon as an optional parameter? No one really uses icon data. Also, it would be helpful to just add the phone button as it is a common auth method - probably a lot more common than some of the ones currently on the list.

**Comment by ZaynJarvis** [comment]
> > can use ButtonBuilder
> 
> At least in the button builder couldn't you add an Icon as an optional parameter? No one really uses icon data. Also, it would be helpful to just add the phone button as it is a common auth method - probably a lot more common than some of the ones currently on the list.

make sense. Will add
