### ISSUE TITLE
Is this following any of the design guidelines from Google? 

### ISSUE THREAD

**Issue by marvlm** [ZaynJarvis/Flutter-Sign-in-Button#7]
I'm referring to the ones listed in the following link:

https://developers.google.com/identity/branding-guidelines

Thanks!

**Comment by ZaynJarvis** [comment]
Sorry, strictly, it's not.
The plugin is inspired by the repo https://github.com/lipis/bootstrap-social 
However, I do recognize the necessity to follow the Google guidelines and will change the Google style in future.

Thank you.

**Comment by marvlm** [comment]
I see, thank you for your answer, I think as it is now it helps in what I'm doing but yes, it will be better to have it updated. 

In another topic, I needed to have a different Sign In text than "Sign in with" because I'm building an app in Spanish and I make the change but when tried to push the branch I created with the change to send you the pull request it says I can't. 

$ git push origin SingInTextChange
remote: Permission to ZaynJarvis/Flutter-Sign-in-Button.git denied to marvlm.
fatal: unable to access 'https://github.com/ZaynJarvis/Flutter-Sign-in-Button.git/': The requested URL returned error: 403

**Comment by ZaynJarvis** [comment]
I will try my best to update the version subject to principle. Thank you for letting me be aware of it. 

As for changing text, you can do so through ButtonBuilder, it’s a feature provided by PR #4. 

If it still doesn’t fit with your need, as u cannot push directly to my repo, u may choose to fork the repository and then update a version on your own repository and make a pull request. 

Thank you for your contribution!

**Comment by ThinkDigitalRepair** [comment]
I was coming here to ask the same thing. I was thinking this would be along the official guidelines. Thanks for putting it up there! But I'll have to keep looking for now

**Comment by ZaynJarvis** [comment]
This issue has been solved thx to the help of @tariq86 and published in 0.5.0
