### ISSUE TITLE
Twitter button not integrated

### ISSUE THREAD

**Issue by dejavu88** [ZaynJarvis/Flutter-Sign-in-Button#8]
This package is really helpful but there is no twitter button ??

**Comment by ZaynJarvis** [comment]
Haha that sounds fair, would you mind making a pull request for that?
All you need is to find a twitter icon in the font-awesome library and then find the correct twitter color

**Comment by ZaynJarvis** [comment]
Have been integrated into 0.2.6 Cheers!
