### ISSUE TITLE
Buttons.Email don't reflect the 'mini: true' property

### ISSUE THREAD

**Issue by leomachadorocha** [ZaynJarvis/Flutter-Sign-in-Button#9]
This is the code. It still shows "Sign In with Email" text.
`SignInButton(
  Buttons.Email,
  mini: true,
  onPressed: () {
    _handleSignIn();
  },
),`

**Comment by ZaynJarvis** [comment]
Have been fixed in version 0.2.6

**Comment by ZaynJarvis** [comment]
Thx for spotting the issue!
