### ISSUE TITLE
Unable to load asset

### ISSUE THREAD

**Issue by SudhanshuR37** [ZaynJarvis/Flutter-Sign-in-Button#92]
While using the built-in buttons in my project, I am this error:

Unable to load asset: packages/flutter_signin_button/assets/logos/google_light.png

Please help!

**Comment by aibi10** [comment]
How did you correct this error?

**Comment by ycagri** [comment]
@aibi10 Did you find the root cause of the exception? `multidexEnabled true` solved my issue for Android devices.
